name: Check formatting

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  check-generated:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
          
      - name: Format files
        run: deno fmt
        
      - name: Run rebuild script
        run: ./tools/rebuild.ts
        
      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Found changes after running formatters and generators:"
            git diff
            exit 1
          fi
